apiVersion: apps/v1
kind: Deployment
metadata:
  name: resiliency1-key-store
  labels:
    app: resiliency1-key-store
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resiliency1-key-store
  template:
    metadata:
      labels:
        app: resiliency1-key-store
        tier: backend
    spec:
      containers:
      - name: resiliency1-key-store
        image: resiliency1-key-store
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 7480

---

apiVersion: v1
kind: Service
metadata:
  name: resiliency1-key-store
  labels:
    app: resiliency1-key-store
    tier: backend
spec:
  ports:
  - port: 7480
    targetPort: 7480
  selector:
    app: resiliency1-key-store
    tier: backend
