apiVersion: apps/v1
kind: Deployment
metadata:
  name: resiliency2-key-store-throttle
  labels:
    app: resiliency2-key-store-throttle
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resiliency2-key-store-throttle
  template:
    metadata:
      labels:
        app: resiliency2-key-store-throttle
        tier: backend
    spec:
      containers:
      - name: resiliency2-key-store-throttle
        image: resiliency2-key-store
        imagePullPolicy: IfNotPresent
        env:
        - name: WINDOW_SIZE_IN_MINUTE
          value: "0.5"
        - name: REQUEST_PER_WINDOW
          value: "3"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 7480

---

apiVersion: v1
kind: Service
metadata:
  name: resiliency2-key-store-throttle
  labels:
    app: resiliency2-key-store-throttle
    tier: backend
spec:
  ports:
  - port: 7480
    targetPort: 7480
  selector:
    app: resiliency2-key-store-throttle
    tier: backend
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resiliency2-server-throttle
  labels:
    app: resiliency2-server-throttle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resiliency2-server-throttle
      tier: frontend
  template:
    metadata:
      labels:
        app: resiliency2-server-throttle
        tier: frontend
    spec:
      containers:
      - name: resiliency2-server-throttle
        image: resiliency2-server
        imagePullPolicy: IfNotPresent
        env:
        - name: KEY_VALUE_STORE_HOST
          value: "$(RESILIENCY2_KEY_STORE_THROTTLE_SERVICE_HOST)"
        - name: KEY_VALUE_STORE_PORT
          value: "$(RESILIENCY2_KEY_STORE_THROTTLE_SERVICE_PORT)"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: resiliency2-server-throttle
  labels:
    app: resiliency2-server-throttle
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: resiliency2-server-throttle
    tier: frontend
  ports:
    - nodePort: 32212
      port: 8080
