apiVersion: apps/v1
kind: Deployment
metadata:
  name: architectural-key-store
  labels:
    app: architectural-key-store
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architectural-key-store
  template:
    metadata:
      labels:
        app: architectural-key-store
        tier: backend
    spec:
      containers:
      - name: architectural-key-store
        image: architectural-key-store
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 7480

---

apiVersion: v1
kind: Service
metadata:
  name: architectural-key-store
  labels:
    app: architectural-key-store
    tier: backend
spec:
  ports:
  - port: 7480
    targetPort: 7480
  selector:
    app: architectural-key-store
    tier: backend
    
---    
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: architectural-bad
  labels:
    app: architectural-bad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architectural-bad
      tier: frontend
  template:
    metadata:
      labels:
        app: architectural-bad
        tier: frontend
    spec:
      containers:
      - name: architectural-bad
        image: architectural-bad
        imagePullPolicy: IfNotPresent
        env:
        - name: KEY_VALUE_STORE_HOST
          value: "$(ARCHITECTURAL_KEY_STORE_SERVICE_HOST)"
        - name: KEY_VALUE_STORE_PORT
          value: "$(ARCHITECTURAL_KEY_STORE_SERVICE_PORT)"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: architectural-bad
  labels:
    app: architectural-bad
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: architectural-bad
    tier: frontend
  ports:
    - nodePort: 32420
      port: 8080
