apiVersion: apps/v1
kind: Deployment
metadata:
  name: architectural-logger-hexagonal
  labels:
    app: architectural-logger-hexagonal
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architectural-logger-hexagonal
  template:
    metadata:
      labels:
        app: architectural-logger-hexagonal
        tier: backend
    spec:
      containers:
      - name: architectural-logger-hexagonal
        image: architectural-logger-hexagonal
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 7080

---

apiVersion: v1
kind: Service
metadata:
  name: architectural-logger-hexagonal
  labels:
    app: architectural-logger-hexagonal
    tier: backend
spec:
  ports:
  - port: 7080
    targetPort: 7080
  selector:
    app: architectural-logger-hexagonal
    tier: backend
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: architectural-key-store-hexagonal
  labels:
    app: architectural-key-store-hexagonal
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architectural-key-store-hexagonal
  template:
    metadata:
      labels:
        app: architectural-key-store-hexagonal
        tier: backend
    spec:
      containers:
      - name: architectural-key-store-hexagonal
        image: architectural-key-store-hexagonal
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 7480

---

apiVersion: v1
kind: Service
metadata:
  name: architectural-key-store-hexagonal
  labels:
    app: architectural-key-store-hexagonal
    tier: backend
spec:
  ports:
  - port: 7480
    targetPort: 7480
  selector:
    app: architectural-key-store-hexagonal
    tier: backend
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: architectural-hexagonal
  labels:
    app: architectural-hexagonal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architectural-hexagonal
      tier: frontend
  template:
    metadata:
      labels:
        app: architectural-hexagonal
        tier: frontend
    spec:
      containers:
      - name: architectural-hexagonal
        image: architectural-hexagonal
        imagePullPolicy: IfNotPresent
        env:
        - name: LOGGER_HOST
          value: "$(ARCHITECTURAL_LOGGER_HEXAGONAL_SERVICE_HOST)"
        - name: LOGGER_PORT
          value: "$(ARCHITECTURAL_LOGGER_HEXAGONAL_SERVICE_PORT)"
        - name: KEY_VALUE_STORE_HOST
          value: "$(ARCHITECTURAL_KEY_STORE_HEXAGONAL_SERVICE_HOST)"
        - name: KEY_VALUE_STORE_PORT
          value: "$(ARCHITECTURAL_KEY_STORE_HEXAGONAL_SERVICE_PORT)"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: architectural-hexagonal
  labels:
    app: architectural-hexagonal
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: architectural-hexagonal
    tier: frontend
  ports:
    - nodePort: 32221
      port: 8080
