apiVersion: apps/v1
kind: Deployment
metadata:
  name: idempotency-good
  labels:
    app: idempotency-good
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idempotency-good
      tier: frontend
  template:
    metadata:
      labels:
        app: idempotency-good
        tier: frontend
    spec:
      containers:
      - name: idempotency-good
        image: idempotency-good
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: idempotency-good
  labels:
    app: idempotency-good
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: idempotency-good
    tier: frontend
  ports:
    - nodePort: 31200
      port: 8080
