apiVersion: apps/v1
kind: Deployment
metadata:
  name: immutability-good
  labels:
    app: immutability-good
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immutability-good
      tier: frontend
  template:
    metadata:
      labels:
        app: immutability-good
        tier: frontend
    spec:
      containers:
      - name: immutability-good
        image: immutability-good
        imagePullPolicy: IfNotPresent
        env:
        - name: GET_HOSTS_FROM
          value: "$(REDIS_SERVICE_HOST)"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: immutability-good
  labels:
    app: immutability-good
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: immutability-good
    tier: frontend
  ports:
    - nodePort: 30200
      port: 8080
